producer:
  topic: anime-events
  compression: gzip
  max_messages_per_batch: 100000
  data_path: ../UserAnimeList.csv

hadoop:
  user: ubuntu

hive:
  port: 10000
  user: hive
  database: anime
  table: user_score
  settings:
    hive.execution.engine: tez
